import { AppProps } from "next/app";
import { ThemeProvider } from "styled-components";
import Global from "../styles/global";

import theme from "../styles/theme";

import { Noto_Sans_KR } from "next/font/google";
import Head from "next/head";

const notoSansKr = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const _app = ({ Component }: AppProps) => {
  return (
    <>
      <Head>
        <title>모두의 이력서</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={notoSansKr.className}>
        <ThemeProvider theme={theme}>
          <Global />
          <Component />
        </ThemeProvider>
      </main>
    </>
  );
};

export default _app;
