import { useState } from "react";
import Head from "next/head";
import { AppProps } from "next/app";
import { Noto_Sans_KR } from "next/font/google";
import { useRouter } from "next/router";
import { ThemeProvider } from "styled-components";

import Header from "../components/layout/header/Header";
import Float from "../components/layout/Float";

import theme from "../styles/theme";
import Global from "../styles/global";
import { ThemeContext } from "../context/themeContext";

const notoSansKr = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const _app = ({ Component }: AppProps) => {
  const router = useRouter();

  const derkMode =
    typeof window !== "undefined" ? localStorage.getItem("isDark") : null;
  const [isDark, setIsDark] = useState(derkMode ? true : false);

  return (
    <>
      <Head>
        <title>모두의 이력서</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={notoSansKr.className}>
        <ThemeContext.Provider value={{ isDark, setIsDark }}>
          <ThemeProvider theme={theme}>
            <Global mode={isDark ? "darkTheme" : "lightTheme"} />
            {router.query.header !== "N" && <Header />}
            <Float />
            <Component />
          </ThemeProvider>
        </ThemeContext.Provider>
      </main>
    </>
  );
};

export default _app;
